### ISSUE TITLE
Terminology (and associated types)

### ISSUE THREAD

**Issue by arteymix** [rainwoodman/vast#12]
All this should probably end-up in the wiki.

## Dimension

Number of independent axes.

 - `dimension` is `size_t` as it defines the size of `strides` and `shape`

## Axis

 - `ssize_t` from the outside world for negative indexing
 - `size_t` internally for indexing `strides` and `shape`
 - plural form is axes

## Index

 - `ssize_t[]` to allow negative indexing
 - length is implicitly given by the dimension
 - computes a `size_t` offset using strides and shape

## Offset

 - `size_t` to index the raw memory

## Strides

 - `ssize_t[]` to allow negative indexing
 - length is implicitly given by the dimension

## Shape

 - `size_t[]` as it define the length of each axes
 - length is implicitly given by the dimension

## Scalar

The scalar are the atoms of a dense array.

 - `scalar_size` is a `size_t`
 - `scalar_type` is a `GType`

## Raw memory

 - `GBytes` that wraps a `uint8[]` array

**Comment by arteymix** [comment]
Just to mention, all the `size_t` and `ssize_t` are refeering to `gsize` and `gssize` as described in https://developer.gnome.org/glib/stable/glib-Basic-Types.html They are alias with introspection.

**Comment by rainwoodman** [comment]
1.In general `offset` could be negative. I know it is impossible if it is GBytes. If it turns out necessary we can always flip.
1. in `numpy`, the argument `newshape`  to  `reshape(newshape)` is signed. If a newshape is [-1] it will be automatically inferred from the total size and the non `-1` elements.  Very handy feature. but it means sometimes shape can be `ssize_t` too.

Would it hurt if we make all offsets / shapes are ssize_t?

**Comment by arteymix** [comment]
I like to keep everything unsigned internally and signed externally to compute reverse offset/index.

We never really expose offsets, only via indexes which are already signed.

For `reshape` wouldn't it be nicer to fill smallest size first? Instead of having `-1` for inferred dimension, we could have something like `size_t.MAX` for unconstrained axes.

``` vala
arr.reshape ({2, 2, size_t.MAX}); // fill 2 by 2 and as much as possible in the last axis
```

**Comment by rainwoodman** [comment]
That's a great idea!

**Comment by arteymix** [comment]
I moved everything into the wiki: https://github.com/rainwoodman/vast/wiki/Types-and-Terminology

I will copy the comment about reshaping in #7.
