### ISSUE TITLE
zero dim array shall have a size of 1. 

### ISSUE THREAD

**Issue by rainwoodman** [rainwoodman/vast#24]
It is a scalar.

**Comment by arteymix** [comment]
However, the shape and strides are empty, no?

**Comment by rainwoodman** [comment]
Yes.

**Comment by rainwoodman** [comment]
They are empty. 
I also think of it this way. size = product(shape).
the identity of product operator is 1. So if len(shape) == 0, the product shall be 1.

**Comment by arteymix** [comment]
I fixed that and added some tests in 97f95d75a567d19338efca1b9033c919e07fb251

I just had to fix the specific case of empty array and did not notice that dimension 0 were used for scalars. I added tests to ensure correct behaviours.

**Comment by arteymix** [comment]
We can index scalar array with `array.get_value ({})`. I think it's good for now with the tests.
